name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check formatting
        run: nix develop -c treefmt --fail-on-change
      - name: Run lint
        run: nix develop -c yarn lint
